development:
  adapter:  mysql2
  pool:     5
  timeout:  5000
  username: jcarson
  password: vice*sage
  hostname: localhost
  database: msu1tracks_development
production:
  adapter:  mysql2
  pool:     5
  timeout:  5000
  username: msu1tracks
  password: ring*fold
  hostname: localhost
  database: msu1tracks_production
