icons:
  download: fa-download
  home:     fa-home
  music:    fa-music
  news:     fa-newspaper-o
  github:   fa-github
  change:   fa-long-arrow-right
  clock:    fa-clock-o
  models:
    console:        fa-gamepad
    videogame:      fa-desktop
    msu1_pack:      fa-archive
    msu1_pcm_track: fa-music
