consoles:
  nes:
    friendly_name: NES 
    videogames:
      legacy_of_the_wizard:
        friendly_name: Legacy of the Wizard
  n64:
    friendly_name: N64
    videogames:
      mystical_ninja_starring_goemon:
        friendly_name: Mystical Ninja Starring Goemon
  snes:
    friendly_name: SNES
    videogames:
      a_link_to_the_past:
        friendly_name: A Link to the Past
        msu1_patches:
          standard:
            friendly_name: Standard
            filename_prefix: alttp_msu
            tracks:
              1:  
                friendly_name: Triforce / Title Screen
              2:  
                friendly_name: Lightworld
              3:  
                friendly_name: Rain
              4:  
                friendly_name: Dark World (Rabbit)
              5:  
                friendly_name: Lost Woods
              6:  
                friendly_name: Introduction
              7:  
                friendly_name: Kakariko Village
              8:  
                friendly_name: Portal
              9:  
                friendly_name: Dark World (Moon Pearl)
              10: 
                friendly_name: Master Sword
              11: 
                friendly_name: File Select Screen
              12: 
                friendly_name: Guards Attacking
              13: 
                friendly_name: Skull Woods / Dark Death Mountain
              14: 
                friendly_name: Minigame
              15: 
                friendly_name: Title Screen
              16: 
                friendly_name: Hyrule Castle
              17: 
                friendly_name: Pendant Dungeon
              18: 
                friendly_name: Cave 1
              19: 
                friendly_name: Dungeon Cleared
              20: 
                friendly_name: Sanctuary
              21: 
                friendly_name: Boss Fight
              22: 
                friendly_name: Crystal Dungeon
              23: 
                friendly_name: Fortune Teller
              24: 
                friendly_name: Cave 2
              25: 
                friendly_name: Zelda Rescued
              26: 
                friendly_name: Crystal Acquired
              27: 
                friendly_name: Fairy
              28: 
                friendly_name: Ganon's Theme Only
              29: 
                friendly_name: Ganon Appears
              30: 
                friendly_name: Face to Face + Ganon's Theme
              31: 
                friendly_name: Ganon Battle
        msu1_packs:
          legacy_of_the_wizard:
            patch:          standard
            friendly_name:  Legacy of the Wizard
            mapping:
              1: 
                # Triforce / Title Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              2: 
                # Lightworld
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0013_near_home
              3: 
                # Rain
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0001_dungeon_entrance
              4: 
                # Dark World (Rabbit)
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0002_warriors_theme
              5: 
                # Lost Woods
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              6: 
                # Introduction
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              7: 
                # Kakariko Village
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0008_welcome
              8:
                # Portal
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0015_treasure_chest
              9: 
                # Dark World (Moon Pearl)
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0004_elfs_theme
              10: 
                # Master Sword
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              11: 
                # File Select Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              12: 
                # Guards Attacking
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0011_dragon_slayers
              13: 
                # Skull Woods / Dark Death Mountain
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0016_unknown_bonus_track
              14: 
                # Minigame
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0012_guardian_of_the_crown
              15: 
                # Title Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              16: 
                # Hyrule Castle
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0002_warriors_theme
              17: 
                # Pendant Dungeon
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0001_dungeon_entrance
              18: 
                # Cave 1
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0005_monsters_theme
              19: 
                # Dungeon Cleared
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              20: 
                # Sanctuary
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0014_preparations
              21: 
                # Boss Fight
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0006_king_dragon_keela
              22: 
                # Crystal Dungeon
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0003_wizards_theme
              23: 
                # Fortune Teller
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              24: 
                # Cave 2
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0005_monsters_theme
              25: 
                # Zelda Rescued
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              26: 
                # Crystal Acquired
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              27: 
                # Fairy
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0014_preparations
              28: 
                # Ganon's Theme Only
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              29: 
                # Ganon Appears
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              30: 
                # Face to Face + Ganon's Theme
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              31: 
                # Ganon Battle
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0016_unknown_bonus_track
          mystical_ninja_starring_goemon_0001:
            patch:          standard
            friendly_name:  Mystical Ninja Starring Goemon
            mapping:
              1: 
                # Triforce / Title Screen
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0001_theme_of_mystical_ninja
              2: 
                # Lightworld
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0007_the_journey_begins_on_mt_fuji_road
                #track:     0009x_kai_highway_other_intro_1
                #track:     0009x_kai_highway_other_intro_2
                #track:     0019_yamato
                #track:     0026_sunset_want_you
              3: 
                # Rain
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0025_our_kidnapped_kids_
              4: 
                # Dark World (Rabbit)
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0044_the_deep_flickering_white_shadow
              5: 
                # Lost Woods
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0020_ancient_bamboo
              6: 
                # Introduction
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0017_secret_ninja_agent
                #track:     0003_it_happened_on_an_ordinary_day_part_1
                #track:     0003_it_happened_on_an_ordinary_day_part_2
                #track:     0003_it_happened_on_an_ordinary_day_part_4
              7: 
                # Kakariko Village
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0004_flowery_oedo_the_lost_village
                #track:     0005_buy_or_leave
                #track:     0031_farm_village_legend
                #track:     0043_the_melting_snow_goes_along_with_the_festival
              8:
                # Portal
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0099_sfx_kce_logo
              9: 
                # Dark World (Moon Pearl)
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0048_hot_blooded_man_c
                #track:     0048_hot_blooded_man_b
                #track:     0048_hot_blooded_man_a
                #track:     0032_udon_kotarou
              10: 
                # Master Sword
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0035_battery_of_the_heart
              11: 
                # File Select Screen
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0021_heartbeat_bossa_nova
              12: 
                # Guards Attacking
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0041_crisis
              13: 
                # Skull Woods / Dark Death Mountain
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0024_stairs_of_regret
              14: 
                # Minigame
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0039_oni_oni_redezvous
                #track:     0009x_apparition_in_the_middle_of_the_lake_without_intro
                #track:     0027_fallen_food_mini_ebisu
                #track:     0042_bucchigiri_banzai
                #track:     0046_waterfall_of_kegon
                #track:     0049_apparition_in_the_middle_of_the_lake
              15: 
                # Title Screen
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0002_i_am_impact
              16: 
                # Hyrule Castle
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0009_rescue_the_feudal_lord_b
                #track:     0009_rescue_the_feudal_lord_a
              17: 
                # Pendant Dungeon
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0028_childhood_toy_behind_you_c
                #track:     0028_childhood_toy_behind_you_b
                #track:     0028_childhood_toy_behind_you_a
              18: 
                # Cave 1
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0022_blue_sky_blue_dragon_a
                #track:     0022_blue_sky_blue_dragon_b
                #track:     0022_blue_sky_blue_dragon_c
                #track:     0008_wait_a_sec_im_coming
                #track:     0033_within_the_burning_sands
                #track:     0036_depths_of_darkness
                #track:     0045_come_baby_come
              19: 
                # Dungeon Cleared
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0016_another_win_for_us
              20: 
                # Sanctuary
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0050_holy_ground_pemopemo
                #track:     0018_a_zen_spirit_burns_crimson
              21: 
                # Boss Fight
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0029_heartbreak_corlin
                #track:     0011_im_warning_you_youll_get_burned
                #track:     0014_a_disaster
                #track:     0015_warriors
                #track:     0038_ghost_attack
                #track:     0055_little_baby_sleepin
              22: 
                # Crystal Dungeon
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0037_use_the_ice_kunai_on_the_foxs_fire_c
                #track:     0037_use_the_ice_kunai_on_the_foxs_fire_b
                #track:     0037_use_the_ice_kunai_on_the_foxs_fire_a
              23: 
                # Fortune Teller
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0006_secrets_of_old_man_plasma
                #track:     0010_voluptuous_cauliflower
              24: 
                # Cave 2
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0033_within_the_burning_sands
              25: 
                # Zelda Rescued
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0013_the_lord_and_princess_yuki
              26: 
                # Crystal Acquired
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0012_easy_victory_get_a_way
                #track:     0054_gorgeous_my_stage
                #track:     0023_twilight_koryuta
              27: 
                # Fairy
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0034_gods_giant_tree
                #track:     0047_airy_mermaid
              28: 
                # Ganon's Theme Only
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0030_domineering_march
                #track:     0009x_dark_de_bad_na_easy_yo_without_intro
              29: 
                # Ganon Appears
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0009x_dark_de_bad_na_easy_yo_without_intro
              30: 
                # Face to Face + Ganon's Theme
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0009x_dark_de_bad_na_easy_yo_without_intro
              31: 
                # Ganon Battle
                console:   n64
                videogame: mystical_ninja_starring_goemon
                track:     0053_goe_goe_spark
                #track:     0051_kabuking
              # credits?
              # 0052_sogen_street
