consoles:
  nes:
    friendly_name: NES 
    videogames:
      legacy_of_the_wizard:
        friendly_name: Legacy of the Wizard
  snes:
    friendly_name: SNES
    videogames:
      a_link_to_the_past:
        friendly_name: A Link to the Past
        msu1_patch:
          tracks:
            1:  Triforce / Title Screen
            2:  Lightworld
            3:  Rain
            4:  Dark World (Rabbit)
            5:  Lost Woods
            6:  Introduction
            7:  Kakariko Village
            8:  Portal
            9:  Dark World (Moon Pearl)
            10: Master Sword
            11: File Select Screen
            12: Guards Attacking
            13: Skull Woods / Dark Death Mountain
            14: Minigame
            15: Title Screen
            16: Hyrule Castle
            17: Pendant Dungeon
            18: Cave 1
            19: Dungeon Cleared
            20: Sanctuary
            21: Boss Fight
            22: Crystal Dungeon
            23: Fortune Teller
            24: Cave 2
            25: Zelda Rescued
            26: Crystal Acquired
            27: Fairy
            28: Ganon's Theme Only
            29: Ganon Appears
            30: Face to Face + Ganon's Theme
            31: Ganon Battle
          msu1_packs:
            - name:  Legacy of the Wizard
              patch_for:
                console:   snes
                videogame: a_link_to_the_past
              tracks:
                1: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
