consoles:
  nes:
    friendly_name: NES 
    videogames:
      legacy_of_the_wizard:
        friendly_name: Legacy of the Wizard
  n64:
    friendly_name: N64
    videogames:
      mystical_ninja_starring_goemon:
        friendly_name: Mystical Ninja Starring Goemon
  snes:
    friendly_name: SNES
    videogames:
      a_link_to_the_past:
        friendly_name: A Link to the Past
        msu1_patches:
          standard:
            friendly_name: Standard
            filename_prefix: alttp_msu
            tracks:
              1:  
                friendly_name: Triforce / Title Screen
              2:  
                friendly_name: Lightworld
              3:  
                friendly_name: Rain
              4:  
                friendly_name: Dark World (Rabbit)
              5:  
                friendly_name: Lost Woods
              6:  
                friendly_name: Introduction
              7:  
                friendly_name: Kakariko Village
              8:  
                friendly_name: Portal
              9:  
                friendly_name: Dark World (Moon Pearl)
              10: 
                friendly_name: Master Sword
              11: 
                friendly_name: File Select Screen
              12: 
                friendly_name: Guards Attacking
              13: 
                friendly_name: Skull Woods / Dark Death Mountain
              14: 
                friendly_name: Minigame
              15: 
                friendly_name: Title Screen
              16: 
                friendly_name: Hyrule Castle
              17: 
                friendly_name: Pendant Dungeon
              18: 
                friendly_name: Cave 1
              19: 
                friendly_name: Dungeon Cleared
              20: 
                friendly_name: Sanctuary
              21: 
                friendly_name: Boss Fight
              22: 
                friendly_name: Crystal Dungeon
              23: 
                friendly_name: Fortune Teller
              24: 
                friendly_name: Cave 2
              25: 
                friendly_name: Zelda Rescued
              26: 
                friendly_name: Crystal Acquired
              27: 
                friendly_name: Fairy
              28: 
                friendly_name: Ganon's Theme Only
              29: 
                friendly_name: Ganon Appears
              30: 
                friendly_name: Face to Face + Ganon's Theme
              31: 
                friendly_name: Ganon Battle
        msu1_packs:
          legacy_of_the_wizard:
            patch:          standard
            friendly_name:  Legacy of the Wizard
            mapping:
              1: 
                # Triforce / Title Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              2: 
                # Lightworld
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0013_near_home
              3: 
                # Rain
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0001_dungeon_entrance
              4: 
                # Dark World (Rabbit)
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0002_warriors_theme
              5: 
                # Lost Woods
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              6: 
                # Introduction
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              7: 
                # Kakariko Village
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0008_welcome
              8:
                # Portal
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0015_treasure_chest
              9: 
                # Dark World (Moon Pearl)
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0004_elfs_theme
              10: 
                # Master Sword
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              11: 
                # File Select Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              12: 
                # Guards Attacking
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0011_dragon_slayers
              13: 
                # Skull Woods / Dark Death Mountain
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0016_unknown_bonus_track
              14: 
                # Minigame
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0012_guardian_of_the_crown
              15: 
                # Title Screen
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0010_title_screen
              16: 
                # Hyrule Castle
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0002_warriors_theme
              17: 
                # Pendant Dungeon
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0001_dungeon_entrance
              18: 
                # Cave 1
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0005_monsters_theme
              19: 
                # Dungeon Cleared
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              20: 
                # Sanctuary
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0014_preparations
              21: 
                # Boss Fight
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0006_king_dragon_keela
              22: 
                # Crystal Dungeon
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0003_wizards_theme
              23: 
                # Fortune Teller
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              24: 
                # Cave 2
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0005_monsters_theme
              25: 
                # Zelda Rescued
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              26: 
                # Crystal Acquired
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0007_worzen_family
              27: 
                # Fairy
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0014_preparations
              28: 
                # Ganon's Theme Only
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              29: 
                # Ganon Appears
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              30: 
                # Face to Face + Ganon's Theme
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0009_deaths_theme
              31: 
                # Ganon Battle
                console:   nes
                videogame: legacy_of_the_wizard
                track:     0016_unknown_bonus_track
