consoles:
  nes:
    friendly_name: NES 
    videogames:
      legacy_of_the_wizard:
        friendly_name: Legacy of the Wizard
  snes:
    friendly_name: SNES
    videogames:
      a_link_to_the_past:
        friendly_name: A Link to the Past
        msu1_patches:
          standard:
            friendly_name: Standard
            tracks:
              1:  
                friendly_name: Triforce / Title Screen
              2:  
                friendly_name: Lightworld
              3:  
                friendly_name: Rain
              4:  
                friendly_name: Dark World (Rabbit)
              5:  
                friendly_name: Lost Woods
              6:  
                friendly_name: Introduction
              7:  
                friendly_name: Kakariko Village
              8:  
                friendly_name: Portal
              9:  
                friendly_name: Dark World (Moon Pearl)
              10: 
                friendly_name: Master Sword
              11: 
                friendly_name: File Select Screen
              12: 
                friendly_name: Guards Attacking
              13: 
                friendly_name: Skull Woods / Dark Death Mountain
              14: 
                friendly_name: Minigame
              15: 
                friendly_name: Title Screen
              16: 
                friendly_name: Hyrule Castle
              17: 
                friendly_name: Pendant Dungeon
              18: 
                friendly_name: Cave 1
              19: 
                friendly_name: Dungeon Cleared
              20: 
                friendly_name: Sanctuary
              21: 
                friendly_name: Boss Fight
              22: 
                friendly_name: Crystal Dungeon
              23: 
                friendly_name: Fortune Teller
              24: 
                friendly_name: Cave 2
              25: 
                friendly_name: Zelda Rescued
              26: 
                friendly_name: Crystal Acquired
              27: 
                friendly_name: Fairy
              28: 
                friendly_name: Ganon's Theme Only
              29: 
                friendly_name: Ganon Appears
              30: 
                friendly_name: Face to Face + Ganon's Theme
              31: 
                friendly_name: Ganon Battle
          msu1_packs:
            legacy_of_the_wizard:
              friendly_name:  Legacy of the Wizard
              mapping:
                1: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                2: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                3: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                4: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                5: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                6: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                7: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                8: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                9: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                10: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                11: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                12: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                13: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                14: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                15: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                16: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                17: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                18: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                19: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                20: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                21: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                22: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                23: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                24: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                25: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                26: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                27: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                28: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                29: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                30: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
                31: 
                  console:   nes
                  videogame: legacy_of_the_wizard
                  track:     0010_title_screen
